#!/bin/bash
#
# nswl		Start up the Netscaler Logging server daemon

### BEGIN INIT INFO
# Provides: nswl
# Required-Start: $local_fs $network $syslog
# Required-Stop: $local_fs $syslog
# Should-Start: $syslog
# Should-Stop: $network $syslog
# Default-Start: 2 3 4 5
# Default-Stop: 0 1 6
# Short-Description: Start up the Netscaler Logging server daemon
# Description:       nswl is a netscaler logging deamon
### END INIT INFO

# source function library
. /etc/rc.d/init.d/functions

case "$1" in
	start)
		echo -n "starting Netscaler: nswl -start -f /usr/local/netscaler/etc/log.conf&"
		/usr/local/netscaler/bin/nswl -start -f /usr/local/netscaler/etc/log.conf&
		;;
	stop)
		echo -n "stoping netscaler: nswl -stop"
		/usr/local/netscaler/bin/nswl -stop
		;;
	restart)
		echo -n "restarting netscaler"
		/usr/local/netscaler/bin/nswl -stop
		/usr/local/netscaler/bin/nswl -start -f /usr/local/netscaler/etc/log.conf&
		;;
esac
